### ISSUE TITLE
关于spade

### ISSUE THREAD

**Issue by NH4HCr2O7** [MoHaDouBiTeam/gregtech6-chinese-translation#16]
@Tanimodori 工兵铲已改为万能锹……也许我应该再考虑一下……或许平头铲比单纯的铲子好些？
提案：1：尖头铲头
2：铲头
3：平头铲
4：方块采掘铲

**Comment by indoorsNB** [comment]
这....有点尴尬啊……我这个主要汉化者居然一个月没更新了
