### ISSUE TITLE
实用扩展(Actually Additions)材料译名征集

### ISSUE THREAD

**Issue by Tanimodori** [MoHaDouBiTeam/gregtech6-chinese-translation#34]
AA里面新加入的几种材料方块（原名/"官方"译名）：

- Restonia Crystal Block/红石水晶块
- Palis Crystal Block/青金石水晶块
- Diamatine Crystal Block/钻石水晶块
- Emeradic Crystal Block/绿宝石水晶块
- Void Crystal Block/煤晶块
- Enori Crystal Block/铁晶块

这些材料是使用对应的原材料在AA的分子再构机（其实我觉得这是台湾译法，我觉得reconstructor应该译作重构机）里面吃RF生成的，如果直接引用原名势必容易引发混乱，故现在征求翻译意见。

一些备选方案：

1. 直接使用官方译名
2. 将关键词音译（Enori ->埃诺利）
3. 加上修饰词（Restonia->重构红石）

你们觉得哪种方案好？

**Comment by NH4HCr2O7** [comment]
1.
可在OreDict处注明AA

**Comment by Tanimodori** [comment]
“红石(AA)水晶块”这样？我还是觉得3好。

**Comment by JackyJnirvana** [comment]
1. 加修饰词吧
2. 在名称里注明[AA] (之前对付mfr牛奶时貌似用过类似的做法
3. 我去找其他译者问问…

**Comment by indoorsNB** [comment]
3我感觉挺好

**Comment by Tanimodori** [comment]
经讨论决定采用以下译名：

- Restonia Crystal Block/再构红石水晶块
- Palis Crystal Block/再构青金石水晶块
- Diamatine Crystal Block/再构钻石水晶块
- Emeradic Crystal Block/再构绿宝石水晶块
- Void Crystal Block/再构煤晶块
- Enori Crystal Block/再构铁晶块

**Comment by Tanimodori** [comment]
出于以下两点原因，现在改用选项1

1. 原名没有引发混乱
2. 为了方便玩家在NEI中搜索
3. 先到先得原则
4. 译名统一原则
