### ISSUE TITLE
关于那堆奇怪的花的考据

### ISSUE THREAD

**Issue by Tanimodori** [MoHaDouBiTeam/gregtech6-chinese-translation#35]
原文/_学名_/中文译名/考据

- Altered Andesite Buckwheat/_Eriogonum robustum_/粗壮[绒毛蓼]/robustum->robust
- Crosby Buckwheat/_Eriogonum crosbyae_/克罗斯比[绒毛蓼]
- Alpine Catchfly/_Silene suecica_/瑞典[蝇子草]/suecica->suecicus->Swedish->瑞典的
- Viola Calaminaria/_Viola Calaminaria_/卡拉明[堇菜]/Calaminaria->Calamine->卡拉明
- Thlaspi Lereschianum/_Thlaspi Lereschianum_/勒雷舍[遏蓝菜]/Lereschianum->lereschianus->Louis François Jules Rodolphe Leresche->勒雷舍
- Tufted Evening Primrose/_Oenothera biennis_/丛生[月见草]
- Narcissus Sheldonia/_???_/谢尔登[水仙花]
- Orechid/[凝矿兰]/植物魔法虚构植物，取自Orchid->兰花
- Big Sagebrush/_Artemisia tridentata_/[三齿蒿]
- Four Wing Saltbush/_Atriplex canescens_/[四翅滨藜]
- Desert Trumpet/_Eriogonum inflatum_/袋状[绒毛蓼]
- Copper Flower Plant/_Acalypha australis_/[铁苋菜]
- Prince's Plume/_Stanleya pinnata_/荒漠圆锥花
- Thompsons Locoweed/_Astragalus mollissimus_/[软毛黄芪]

注：

1. 部分植物没有或尚未找到对应学名
2. 译名可能取自俗名或学名，其中方括号部分为确定通用的译名
3. Buckwheat英语中还可以指绒毛蓼属而不是荞麦属

如果有什么意见或建议欢迎提出

**Comment by NH4HCr2O7** [comment]
全叫绒毛蓼就不大好

**Comment by Tanimodori** [comment]
绒毛蓼属的就三个，而且我还没找到通用的中文俗名只能从学名硬译……

**Comment by NH4HCr2O7** [comment]
我认为可以换种思路，换成我国常见的植物，并且名字要深奥让人看不懂（滑稽）
