### ISSUE TITLE
关于"Motor"的机器翻译修正

### ISSUE THREAD

**Issue by NH4HCr2O7** [MoHaDouBiTeam/gregtech6-chinese-translation#36]
目前已将"Electric Motor"译为“电力旋转动能引擎”
对其进行一次修正，可译为“电动马达”
但与"Compact Electric Motor"冲突
现提出以下几个方案
1.将"Electric Motor"译为“电动马达”，修改"Compact Electric Motor"
2.将"Electric Motor"译为“电动机”或其他同义词
3.保持现状

**Comment by Tanimodori** [comment]
1. [Electric] Motor的规范译名是“电动机”，“马达”是台湾译名，“电动马达”……逐字翻译？
2. Compact是“紧致的”之意，游戏中作为中间件，不能放置，所以我觉得应该把“Compact Electric Motor”译成“紧凑型电动机”。

**Comment by lycc193** [comment]
> 紧凑型电动机

“微型电机”应该更适合吧
