### ISSUE TITLE
关于“Raw”的优化

### ISSUE THREAD

**Issue by NH4HCr2O7** [MoHaDouBiTeam/gregtech6-chinese-translation#37]
例：Raw Arrow Head被翻译粗糙的箭头
个人认为这里不算粗糙的，可以改成粗制的，因为这种是从模具中取出或压模机压制的（万用铲头除外）
或者“浇筑”“钝”等

**Comment by Tanimodori** [comment]
我倒没什么意见，你们讨论出结果通知一下我就行。

**Comment by JackyJnirvana** [comment]
刚铸造或其他粗加工手段做出来，未经过精细加工的工件，我觉得应该叫“毛坯”

**Comment by wu110120119** [comment]
可以叫‘毛坯’

> 国标 _锻造术语_（GB/T5611-1998）
> 铸造－熔炼金属，制造铸型，并将熔融金属浇入铸型，凝固后获得具有一定形状、尺寸和性能金属零件**毛坯**的成型方法
> 铸造是将金属熔炼成符合一定要求的液体并浇进铸型里，经冷却凝固、清整处理后得到有预定形状、尺寸和性能的铸件的工艺过程。**铸造毛坯**因近乎成形，而达到免机械加工或少量加工的目的降低了成本并在一定程度上减少了制作时间．铸造是现代装置制造工业的基础工艺之一。

**Comment by NH4HCr2O7** [comment]
好的就是毛坯了
