### ISSUE TITLE
关于新版格雷对于黄铁矿石名称的修改

### ISSUE THREAD

**Issue by NH4HCr2O7** [MoHaDouBiTeam/gregtech6-chinese-translation#43]
新版黄铁矿石具有和金矿石同样的材质，如图
![2018-02-11_17 18 59](https://user-images.githubusercontent.com/25445995/37238963-a085ded0-246c-11e8-89db-f69c112c553c.png)
同时原版GregTech.lang中对应Pyrite Ore也变成了Gold Ore
显然这是个彩蛋![image](https://user-images.githubusercontent.com/25445995/37238974-f0c38186-246c-11e8-87c7-3c5b1fc0b1c0.png)
所以显然应将黄铁矿石改为金矿石

**Comment by Tanimodori** [comment]
替换器是根据原文而不是字段名来翻译的，所以这个问题并不存在啊……
