### ISSUE TITLE
汉化失败

### ISSUE THREAD

**Issue by Ixyugi** [MoHaDouBiTeam/gregtech6-chinese-translation#47]
我用最新的gregtech.lang文件替换了.Minecraft下的lang文件，重新运行后自动生成了gregtech_error.lang文件，而且并没有成功汉化，不知是什么原因。
PS：格雷6用的是6.07.07

**Comment by Ixyugi** [comment]
哦，我知道了，把里面词条翻译复制然后替换对应文本就行了。尴尬

**Comment by Tanimodori** [comment]
@Ixyugi  Fixed in commit 312fec70acf. Simple bug in file head and tail. Note that now  you may checkout the latest release [here](https://github.com/MoHaDouBiTeam/gregtech6-chinese-translation/releases/latest).
